name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: cs-261287827031-default
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm install --save replicate
      - run: npm install --save openai
      - run: npm install
      - run: npm start
